name: Publish to PyPI

on:
  push:
    branches:
      - publish-testing

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi-package

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.2
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.2"

      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Set PyPI credentials
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Build package
        run: |
          poetry build

      - name: Store as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7 # Optional: Keep artifacts for 7 days (default is 90)
